# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ulpos"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Wang"]
  s.date = "2013-01-04"
  s.description = "U\u{8054}\u{751f}\u{6d3b}\u{5f00}\u{653e}\u{5e73}\u{53f0}\u{662f}\u{4e3a}\u{6e20}\u{9053}\u{5408}\u{4f5c}\u{4f19}\u{4f34}\u{63d0}\u{4f9b}\u{4f18}\u{60e0}\u{5238}\u{7535}\u{5b50}\u{51ed}\u{8bc1}\u{4e0e}\u{94f6}\u{884c}\u{5361}\u{3001}\u{5546}\u{6237}POS\u{673a}\u{5177}\u{8fdb}\u{884c}\u{6570}\u{636e}\u{4ea4}\u{4e92}\u{4e0e}\u{5404}\u{65b9}\u{6e05}\u{7ed3}\u{7b97}\u{7684}\u{652f}\u{6301}\u{5e73}\u{53f0}"
  s.email = "bobwang@unionpaysmart.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ulpos.rb",
    "lib/ulpos/client.rb",
    "lib/ulpos/version.rb"
  ]
  s.homepage = "http://github.com/wxmcan/ulpos"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "ulpos open platform"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["= 1.2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["= 1.2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["= 1.2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

